load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "tracing",
    srcs = glob(["*.c"]),
    hdrs = [],
    strip_include_prefix = "//nfs-ganesha/src",
    deps = [],
)
